CREATE TABLE dataset_desafio_2 (
	`MATRICULA` DECIMAL(38, 0) NOT NULL, 
	`NOME` VARCHAR(57) NOT NULL, 
	`REPROVACOES_DE` DECIMAL(38, 0) NOT NULL, 
	`REPROVACOES_EM` DECIMAL(38, 0) NOT NULL, 
	`REPROVACOES_MF` DECIMAL(38, 0) NOT NULL, 
	`REPROVACOES_GO` DECIMAL(38, 0) NOT NULL, 
	`NOTA_DE` DECIMAL(38, 1) NOT NULL, 
	`NOTA_EM` DECIMAL(38, 1) NOT NULL, 
	`NOTA_MF` DECIMAL(38, 1) NOT NULL, 
	`NOTA_GO` DECIMAL(38, 1), 
	`INGLES` DECIMAL(38, 0), 
	`H_AULA_PRES` DECIMAL(38, 0) NOT NULL, 
	`TAREFAS_ONLINE` DECIMAL(38, 0) NOT NULL, 
	`FALTAS` DECIMAL(38, 0) NOT NULL, 
	`PERFIL` VARCHAR(11) NOT NULL
);
